// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2X1jSRWV-v2pDou7q7tUM3NuiD3ZUWns',
    appId: '1:821021980975:web:79db53aebef25f32de09da',
    messagingSenderId: '821021980975',
    projectId: 'jmlog-109d4',
    authDomain: 'jmlog-109d4.firebaseapp.com',
    storageBucket: 'jmlog-109d4.firebasestorage.app',
    measurementId: 'G-KD768V3CRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmppE2j6Y8Qy2aTOgM_5Blp128Wvgh1Ug',
    appId: '1:821021980975:android:20d8525c71f2ae08de09da',
    messagingSenderId: '821021980975',
    projectId: 'jmlog-109d4',
    storageBucket: 'jmlog-109d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuDHvyGE9xz0TqDrzbswPW5gDnVkH0yfI',
    appId: '1:821021980975:ios:e61483380a235ef6de09da',
    messagingSenderId: '821021980975',
    projectId: 'jmlog-109d4',
    storageBucket: 'jmlog-109d4.firebasestorage.app',
    iosBundleId: 'net.yugu0202.jmlog',
  );

}